package StructJson

type AutoGenerated struct {
	Device struct {
		Ua       string `json:"ua"`
		Height   int    `json:"height"`
		Width    int    `json:"width"`
		Dnt      int    `json:"dnt"`
		Language string `json:"language"`
	} `json:"device"`
	Site struct {
		ID       string `json:"id"`
		Page     string `json:"page"`
		Referrer string `json:"referrer"`
		Hostname string `json:"hostname"`
	} `json:"site"`
	Gdpr struct {
	} `json:"gdpr"`
	Schain struct {
		Ver      string `json:"ver"`
		Complete int    `json:"complete"`
		Nodes    []struct {
			Asi string `json:"asi"`
			Sid string `json:"sid"`
			Hp  int    `json:"hp"`
		} `json:"nodes"`
	} `json:"schain"`
	Bids []struct {
		Bidder string `json:"bidder"`
		Params struct {
			SiteID     string  `json:"siteId"`
			FloorPrice float64 `json:"floorPrice"`
		} `json:"params"`
		Crumbs struct {
			Pubcid string `json:"pubcid"`
		} `json:"crumbs"`
		MediaTypes struct {
			Banner struct {
				Sizes [][]int `json:"sizes"`
			} `json:"banner"`
		} `json:"mediaTypes"`
		AdUnitCode          string  `json:"adUnitCode"`
		TransactionID       string  `json:"transactionId"`
		Sizes               [][]int `json:"sizes"`
		BidID               string  `json:"bidId"`
		BidderRequestID     string  `json:"bidderRequestId"`
		AuctionID           string  `json:"auctionId"`
		Src                 string  `json:"src"`
		BidRequestsCount    int     `json:"bidRequestsCount"`
		BidderRequestsCount int     `json:"bidderRequestsCount"`
		BidderWinsCount     int     `json:"bidderWinsCount"`
		Schain              struct {
			Ver      string `json:"ver"`
			Complete int    `json:"complete"`
			Nodes    []struct {
				Asi string `json:"asi"`
				Sid string `json:"sid"`
				Hp  int    `json:"hp"`
			} `json:"nodes"`
		} `json:"schain"`
		TargetKey int `json:"targetKey"`
	} `json:"bids"`
}
